Ansible_generator/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', include('generate_script.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

generate_script/urls.py
from django.conf.urls import url

from generate_script.views import Index, ConfigureRole, ConfigureRegex, ApplyRegex, ConfigureGlobalVariables, \
    ConfigureHosts, get_output

app_name = "generate_src"

urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'run/$', Index.as_view(), name='run_command'),
    url(r'regex/(?P<role>[-\w]+)/(?P<file_name>[-.\w]+)/(?P<regex_name>[-\s\w]+)$', ConfigureRegex.as_view(),
        name='regex'),
    url(r'apply_regex/(?P<role>[-\w]+)/(?P<file_with_location>[-_/.\w]+)$', ApplyRegex.as_view(), name='apply_regex'),
    url(r'save_regex/$', ConfigureRegex.as_view(), name='save_regex'),
    url(r'config/(?P<pk>[-\w]+)/$', ConfigureRole.as_view(), name='config'),
    url(r'config/(?P<pk>[-\w]+)/(?P<slug>[-_/.\w]+)$', ConfigureRole.as_view(), name='detail_config'),
    url(r'config/global_variables$', ConfigureGlobalVariables.as_view(), name='configure_global_variables'),
    url(r'hosts$', ConfigureHosts.as_view(), name="configure_hosts"),
    url(r'hosts/(?P<group_name>[-\s\w]+)$', ConfigureHosts.as_view(), name="configure_hosts"),
    url(r'hosts/(?P<group_name>[-\s\w.]+)/(?P<host_name>[-\s\w.]+)/(?P<action>[-\s\w]+)', ConfigureHosts.as_view(), name="perform_action"),
    url(r'hosts/(?P<group_name>[-\s\w.]+)/(?P<action>[-\s\w.]+)', ConfigureHosts.as_view(), name="perform_action"),
    url(r"output/$", get_output)
]

generate_script/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

# Create your models here.
class VarsFile(models.Model):
    location = models.CharField(primary_key=True, default="vars/variables.yml", max_length=128)

# ToDo dokumentation: mention that only first variable file is used
class GlobalVariables(models.Model):
    language = models.CharField(max_length=16,
                                choices=(("yaml", "YAML"),
                                         ("none", "Plaintext")),
                                default="yaml")
    text_data = models.TextField(primary_key=True)

class Host(models.Model):
    hostname = models.CharField(max_length=256, primary_key=True)
    port = models.IntegerField(default=22, validators=[MaxValueValidator(65535), MinValueValidator(1)])


class Group(models.Model):
    name = models.CharField(max_length=128, primary_key=True)
    description = models.CharField(max_length=256, blank=True, null=True)
    remote_user = models.CharField(max_length=256, default="root")
    vars_files = models.ManyToManyField(VarsFile, default="vars/variables.yml")
    gather_facts = models.BooleanField(default=True)
    hosts = models.ManyToManyField(Host)

class Category(models.Model):
    position = models.IntegerField(default=9)
    name = models.CharField(max_length=32, primary_key=True, default="General")

    class Meta:
        verbose_name_plural = "Categories"

class Role(models.Model):
    role_description = models.CharField(max_length=32)
    role_name = models.CharField(max_length=128, primary_key=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True, default="General")
    group = models.ManyToManyField(Group)
    build_order = models.IntegerField(default= 99, validators=[MinValueValidator(0),]) # ToDo dokumentacia: spomenut ze chovanie je undefined ak je rovnaky build order
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return self.role_description


class RoleFile(models.Model):
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    template = models.BooleanField(default=False, blank=True)
    filename = models.CharField(max_length=256)
    language = models.CharField(max_length=16,
                                choices=(("yaml", "YAML"),
                                         ("none", "Plaintext")),
                                default="yaml")
    location = models.CharField(max_length=512, default="tasks/")
    text_data = models.TextField(null=True, blank=True)
    binary_data = models.BinaryField(null=True, blank=True)

    def __str__(self):
        return "{}/{}{}".format(self.role.role_name,self.location, self.filename)


class Regexp(models.Model):
    role_file = models.ForeignKey(RoleFile, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    regex = models.CharField(max_length=512)
    value = models.CharField(max_length=512, blank=True, null=True)
    is_global = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = (("name", "is_global"),)


class Value(models.Model):
    id = models.AutoField(primary_key=True)
    role = models.ForeignKey(RoleFile, on_delete=models.CASCADE)
    name = models.CharField(max_length=512)
    value = models.CharField(max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name

generate_script/forms.py
from django import forms

device_access = (
    ('password_change', 'Change password'),
    ('hostname_change', 'Change hostname'),
)

ethernet_attacks = (
    ('mitmf', "MiTM Framework"),
    ('bettercap', "Bettercap"),
    ('thc_ipv6', "THC IPv6 Attack toolkit"),
)

wifi_attacks = (
    ("wifi_connection", "Simple WiFi connection"),
    ("pumpkin_wifi", "Pumpkin wifi"),
    ("aircrack", "Aircrack-ng"),
)

class GenerateScript(forms.Form):
    device_access = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=device_access,
    )

    ethernet_attack_tools = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=ethernet_attacks,
    )

    wifi_attack_tools = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=wifi_attacks,
    )

generate_script/views.py
import os
import re
import subprocess
import zipfile
from itertools import chain
from pathlib import Path

from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, resolve
from django.views.generic import FormView, DetailView, TemplateView, ListView

from Ansible_generator.settings import local_run_storage
from generate_script.ansible import Playbook
from generate_script.utils import generate_zip, check_requirements
from generate_script.forms import GenerateScript
from generate_script.models import Role, RoleFile, Regexp, GlobalVariables, Group, Host


class Index(ListView):
    template_name = 'generate_script/configurator.html'
    model = Role
    storage_location = local_run_storage + "playbook"
    log_location = storage_location + "_log.txt"
    err_log_location = storage_location + "_stderr_log.txt"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ordered_roles"] = Role.objects.all().order_by("build_order")
        if resolve(self.request.path_info).url_name == "run_command":
            context["data"] = Path(self.log_location).read_text()
            if not context["data"]:
                context["data"] = "a"
        return context

    def post(self, request, *args, **kwargs):
        # ToDo: refactor
        if request.POST.get("build"):
            counter = 0
            for role in request.POST.getlist("order_position"):
                db_role = Role.objects.get(role_name=role)
                if db_role.build_order != counter:
                    db_role.build_order = counter
                    db_role.save()
                counter += 1

            for role in request.POST.getlist("enabled"):
                db_role = Role.objects.get(role_name=role)
                db_role.enabled = True
                db_role.save()

            for db_role in Role.objects.all():
                if db_role.role_name not in request.POST.getlist("enabled"):
                    print(db_role.role_name)
                    db_role.enabled = False
                    db_role.save()

            playbook = Playbook().generate_playbook(request)
            file_path = generate_zip(playbook)

            #  source: https://stackoverflow.com/a/36394206
            if os.path.exists(file_path):
                with open(file_path, 'rb') as fh:
                    response = HttpResponse(fh.read(), content_type="application/zip")
                    response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
                    return response
            raise Http404

        if request.POST.get("run"):
            counter = 0
            for role in request.POST.getlist("order_position"):
                db_role = Role.objects.get(role_name=role)
                if db_role.build_order != counter:
                    db_role.build_order = counter
                    db_role.save()
                counter += 1

            for role in request.POST.getlist("enabled"):
                db_role = Role.objects.get(role_name=role)
                db_role.enabled = True
                db_role.save()

            for db_role in Role.objects.all():
                if db_role.role_name not in request.POST.getlist("enabled"):
                    db_role.enabled = False
                    db_role.save()

            playbook = Playbook().generate_playbook(request)
            file_path = generate_zip(playbook)

            if check_requirements() and os.path.exists(file_path):
                zip_ref = zipfile.ZipFile(file_path, 'r')
                zip_ref.extractall(self.storage_location)
                zip_ref.close()

                log_file = open(self.log_location, "wb")
                err_log_file = open(self.err_log_location, "wb")

                try:
                    subprocess.Popen(["ansible-playbook", "-i", "hosts", "playbook.yml"], cwd=self.storage_location, stderr=err_log_file, stdout=log_file)
                except subprocess.CalledProcessError as error:
                    log_file.write(error.output)

                log_file.flush()

                return HttpResponseRedirect(reverse('generate_src:run_command'))
            else:
                raise Http404


class ApplyRegex(DetailView):
    template_name = 'generate_script/detail_config_option.html'
    model = Role
    pk_url_kwarg = "role"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        role = Role.objects.get(role_name=self.kwargs["role"])
        context["files"] = RoleFile.objects.filter(role=role)
        context["is_final"] = True

        if not "file_with_location" in self.kwargs:
            self.kwargs["file_with_location"] = "tasks/main.yml"

        file_name = self.kwargs["file_with_location"].split("/")[-1]
        file_location = "/".join(self.kwargs["file_with_location"].split("/")[:-1]) + "/"
        local_regexps = Regexp.objects.filter(role_file=RoleFile.objects.get(role=role,
                                                                             filename=file_name,
                                                                             location=file_location))
        global_regexps = Regexp.objects.filter(is_global=True)
        context["regexps"] = set(chain(local_regexps, global_regexps))
        file = RoleFile.objects.get(role=role, filename=file_name, location=file_location)

        for x in context["regexps"]:
            file.text_data = re.sub(x.regex, x.value, file.text_data)
            print(file.text_data)

        context["file"] = file
        return context


class ConfigureRegex(DetailView):
    template_name = 'generate_script/detail_config_option.html'
    model = Role
    pk_url_kwarg = "role"

    def post(self, request, *args, **kwargs):
        # ToDo: allow changing also a name of regex (or at least show it as error)
        role = request.POST.get("role")
        role_file = RoleFile.objects.get(filename=request.POST.get("filename"), role=role)
        regex, created = Regexp.objects.get_or_create(name=request.POST.get("name"), role_file=role_file, is_global=bool(request.POST.get("is_global"), ))
        if created:
            try:
                original_regex = Regexp.objects.get(name=request.POST.get("name"), is_global=not bool(request.POST.get("is_global"), ))
                original_regex.delete(keep_parents=True)
            except Regexp.DoesNotExist:
                pass
        regex.value = request.POST.get("input")
        regex.regex = request.POST.get("regex")
        regex.save()

        return HttpResponseRedirect(reverse('generate_src:detail_config', kwargs={'pk': request.POST.get("role"),
                                                                                  "slug": request.POST.get(
                                                                                      "location") + request.POST.get(
                                                                                      "filename")}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        role = Role.objects.get(role_name=self.kwargs["role"])
        file = RoleFile.objects.get(role=role, filename=self.kwargs["file_name"])
        try:
            context["regex"] = Regexp.objects.get(role_file=file, name=self.kwargs["regex_name"])
        except Regexp.DoesNotExist:
            context["regex"] = Regexp.objects.get(name=self.kwargs["regex_name"], is_global=True)

        context["files"] = RoleFile.objects.filter(role=role)
        local_regexps = Regexp.objects.filter(role_file=RoleFile.objects.get(role=role,
                                                                             filename=file.filename,
                                                                             location=file.location))
        global_regexps = Regexp.objects.filter(is_global=True)
        context["regexps"] = set(chain(local_regexps, global_regexps))
        context["file"] = RoleFile.objects.get(role=role,
                                               filename=file.filename,
                                               location=file.location)
        return context


class ConfigureRole(DetailView):
    template_name = 'generate_script/detail_config_option.html'
    model = Role

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        role = Role.objects.get(role_name=self.kwargs["pk"])
        context["files"] = RoleFile.objects.filter(role=role)

        if not "slug" in self.kwargs:
            self.kwargs["slug"] = "tasks/main.yml"

        file_name = self.kwargs["slug"].split("/")[-1]
        file_location = "/".join(self.kwargs["slug"].split("/")[:-1]) + "/"
        local_regexps = Regexp.objects.filter(role_file=RoleFile.objects.get(role=role,
                                                                             filename=file_name,
                                                                             location=file_location))
        global_regexps = Regexp.objects.filter(is_global=True)
        context["regexps"] = set(chain(local_regexps, global_regexps))
        context["file"] = RoleFile.objects.get(role=role,
                                               filename=file_name,
                                               location=file_location)
        return context


class ConfigureGlobalVariables(ListView):
    template_name = 'generate_script/detail_config_global_variables.html'
    model = GlobalVariables

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["file"] = GlobalVariables.objects.first()
        context["regexps"] = Regexp.objects.filter(is_global=True)
        return context

class ConfigureHosts(TemplateView):

generate_script/templates/generate_script/config_global_variables.html
{% extends 'bulma/base.html' %}
{% block content %}
    <div class="columns">

        <div class="column">
            {% block src_details %}
            {% endblock %}
        </div>
        <div class="column is-2">
            <aside class="menu">
                <p class="menu-label">
                    Regexps
                </p>
                <ul class="menu-list">
                    {% if regexps %}
                        {% for x in regexps %}
                            <li>
                                <a href="{% url 'generate_src:regex' role=x.role_file.role.role_name file_name=x.role_file.filename regex_name=x.name %}">
                                    {% if x.is_global %}
                                        <i class="fa fa-globe" aria-hidden="true"></i>{% endif %} {{ x.name }}</a></li>
                        {% endfor %}
                    {% endif %}
                </ul>

            </aside>
        </div>
    </div>
{% endblock %}

generate_script/templates/generate_script/config_options.html
{% extends 'bulma/base.html' %}
{% block content %}
<div class="columns">
    <div class="column is-2">
        <aside class="menu">
  <p class="menu-label">
    Files
  </p>
    {% if files %}
        {% for x in files %}
            <ul class="menu-list">
                <li><a href="{% url 'generate_src:detail_config' pk=x.role.role_name slug=x.location|add:x.filename %}">{{ x.location }}{{ x.filename }}</a></li>
            </ul>
        {% endfor %}
    {% endif %}
</aside>
    </div>
    <div class="column">
            {% block src_details %}
            {% endblock %}
    </div>
    <div class="column is-2">
        <aside class="menu">
  <p class="menu-label">
    Regexps
  </p>
        <ul class="menu-list">
            {% if regexps %}
                {% for x in regexps %}
                        <li><a href="{% url 'generate_src:regex' role=role.role_name file_name=file.filename regex_name=x.name %}">{% if x.is_global %}<i class="fa fa-globe" aria-hidden="true"></i>{% endif %} {{ x.name }}</a></li>
                {% endfor %}
            {% endif %}
        </ul>

</aside>
    </div>
</div>
{% endblock %}

generate_script/templates/generate_script/configurator.html
{% extends 'base.html' %}
{% block content %}
    {% if form.errors %}
        {% for errors in form.errors %}
            <div class="notification is-danger">
            <button class="delete"></button>
                {{ errors }}
            </div>
        {% endfor %}
    {% endif %}

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $( function() {
        $( "#sortable" ).sortable();
        $( "#sortable" ).disableSelection();
        } );
    </script>

    <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
        <ul id="sortable" class="menu-list">
        <label class="label">Order</label>
            {% if ordered_roles %}
                {% for role in ordered_roles %}
                    <li class="ui-state-default">
                        <a>
                            <span class="icon is-small is-left"><i class="fas fa-arrows-alt-v" aria-hidden="true"></i></span>
                            {{ role.role_description }}
                            <input type="checkbox" name="enabled" value="{{ role.role_name }}" title="Enable?" {% if role.enabled %}checked{% endif %}>
                            <input type="hidden" id="fname" name="order_position" value={{ role.role_name }}>
                        </a>
                    </li>
                {% endfor %}
            {% endif %}
        </ul>

        <input class="button is-info" name="run" type="submit" value="Run playbook locally" />
        <input class="button is-primary" name="build" type="submit" value="Build basic playbook" />

    </form>

    {% if data %}
        <hr>
        {% load static %}
        <link href="{% static 'css/prism.css' %}" rel="stylesheet" />
        <style type="text/css">
            .number{
                background-color: transparent;
                font-size: 1em;
                vertical-align: initial;
                min-width: initial;
                margin-right: initial;
                display: initial;
                padding: initial;
            }
        </style>
        <p>Output:</p>
        <pre><code class="language-bash" id="data_output"> </code></pre>
        <script>setInterval(function(){ $.get("/output", function( data ) { $( "#data_output" ).html( data );}); }, 1000);</script>
        <script type="text/javascript" src="{% static 'js/prism.js' %}"></script>
    {% endif %}
{% endblock %}

generate_script/templates/generate_script/detail_config_global_variables.html
{% extends "generate_script/config_global_variables.html" %}
{% block src_details %}
<p class="title">Global variables</p>
<nav class="breadcrumb is-centered" aria-label="breadcrumbs">
  <ul>
    <li>
        <a href=#>
        <span class="icon is-small">
          <i class="fa fa-file" aria-hidden="true"></i>
        </span>
        <span>
            {% if is_final %}
                Original version
            {% else %}
                <u>Original version</u>
            {% endif %}
        </span>
      </a>
    </li>
    <li>
      <a href=#>
        <span class="icon is-small">
          <i class="fa fa-file-alt" aria-hidden="true"></i>
        </span>
          {% if is_final %}
              <u>Final version</u>
          {% else %}
                Final version
          {% endif %}

      </a>
    </li>
  </ul>
</nav>
<hr>
{% load static %}
<link href="{% static 'css/prism.css' %}" rel="stylesheet" />
<style type="text/css">
    .number{
        background-color: transparent;
        font-size: 1em;
        vertical-align: initial;
        min-width: initial;
        margin-right: initial;
        display: initial;
        padding: initial;
    }
</style>

<pre><code class="language-{{ file.language }}">{% if not file.binary_data %}{{ file.text_data }}{% endif %}</code></pre>
<script type="text/javascript" src="{% static 'js/prism.js' %}"></script>
{% endblock %}

generate_script/templates/generate_script/detail_config_option.html
{% extends "generate_script/config_options.html" %}
{% block src_details %}
<p class="title">Role: {{ role.role_name }}</p>
<nav class="breadcrumb is-centered" aria-label="breadcrumbs">
  <ul>
    <li>
      <a href="{% url 'generate_src:detail_config' pk=role.role_name slug=file.location|add:file.filename %}">
        <span class="icon is-small">
          <i class="fa fa-file" aria-hidden="true"></i>
        </span>
        <span>
            {% if is_final %}
                Original version
            {% else %}
                <u>Original version</u>
            {% endif %}
        </span>
      </a>
    </li>
    <li>
      <a href="{% url 'generate_src:apply_regex' role=role.role_name file_with_location=file.location|add:file.filename %}">
        <span class="icon is-small">
          <i class="fa fa-file-alt" aria-hidden="true"></i>
        </span>
          {% if is_final %}
              <u>Final version</u>
          {% else %}
                Final version
          {% endif %}

      </a>
    </li>
  </ul>
</nav>
<hr>
{% load static %}
<link href="{% static 'css/prism.css' %}" rel="stylesheet" />
<style type="text/css">
    .number{
        background-color: transparent;
        font-size: 1em;
        vertical-align: initial;
        min-width: initial;
        margin-right: initial;
        display: initial;
        padding: initial;
    }
</style>

<form action="{% url 'generate_src:save_regex' %}" method="post" id="regex_input">
    <div class="field has-addons">
        {% csrf_token %}
        <input name="role" value="{{ file.role.role_name }}" type="hidden">
        <input name="location" value="{{ file.location}}" type="hidden">
        <input name="filename" value="{{ file.filename}}" type="hidden">
        <div class="control">
            <input name="name" required class=" control input" type="text" placeholder="Name" value="{{ regex.name }}">
        </div>
        <div class="control is-expanded">
            <input name="regex" required class="input" type="text" placeholder="Regex input" value="{{ regex.regex }}">
        </div>
        <div class="control">
            <input name="input" class="input" type="text" placeholder="Value" value="{{ regex.value }}">
        </div>
        <div class="control">
            <input name="is_global" class="checkbox" type="checkbox" placeholder="Global" value="True" {% if regex.is_global %}checked{% endif %}>
        </div>
        <p class="control">
            <button class="button" type="submit">Add regex</button>
        </p>
    </div>
</form>

{% if file.language != "none" %}
<pre><code class="language-{{ file.language }}">{% if not file.binary_data %}{{ file.text_data }}{% endif %}</code></pre>
{% else %}
<pre><code class="language-python">{% if not file.binary_data %}{{ file.text_data }}{% endif %}</code></pre>
{% endif %}
<script type="text/javascript" src="{% static 'js/prism.js' %}"></script>
{% endblock %}

generate_script/templates/generate_script/manage_groups.html
{% extends 'bulma/base.html' %}
{% block content %}
    <div class="columns">
        <div class="column is-2">
            <aside class="menu">
                <p class="menu-label">
                    Groups:
                </p>
                <ul class="menu-list">
                    {% if groups %}
                         {% for group in groups %}
                        <li>
                            <a href="{% url 'generate_src:configure_hosts' group_name=group.name %}">{{ group.name }}</a>
                        </li>
                    {% endfor %}
                    {% endif %}
                </ul>
            </aside>
        </div>
        <div class="column">
            <p class="title">Group name: <span class="title is-normal">{{ group.name }}</span></p>
            <table class="table is-striped is-fullwidth is-hoverable">
                <tbody>
                {% if hosts %}
                    {% for host in hosts %}
                        <tr>
                            <td class="has-text-left">{{ host.hostname }} : {{ host.port }}</td>
                            {# <td class="has-text-right"><a href="{% url 'generate_src:perform_action' action="delete_host" group_name=group.name host_name=host.hostname %}"><i class="fas fa-minus-circle"></i></a> <a href="#"></a></td>#}
                            <td class="has-text-right">
                            <form action="{% url 'generate_src:perform_action' action="delete_host" group_name=group.name host_name=host.hostname %}" method="post">
                                {% csrf_token %}
                                <button type="submit" style="background:none;border:none;padding:0;outline: none;">
                                    <span class="icon is-small is-left"><i style="color: #DD4A68" class="fas fa-minus-circle"></i></span>
                                </button>
                            </form>
                        </td>
                        </tr>
                    {% endfor %}
                {% endif %}
                <tr>
                    <td class="has-text-left">
                        <form action="{% url 'generate_src:perform_action' action="add_new_host" group_name=group.name%}" method="post">
                            {% csrf_token %}
                            <input class="input" style="width:30em;" type="text"
                                   placeholder="Hostname" name="hostname">:<input
                                class="input" style="width:6em;" type="number" value="22" placeholder="Port" name="post">
                    <td class="has-text-right"><button type="submit"><i class="fas fa-plus"></i> Add new host</button> </td>
                    </form>
                </tr>
                </tbody>
            </table>

        </div>
    </div>
{% endblock %}